### PR TITLE
Haskell Data.Sequence Implementation

### PR DESCRIPTION
**Pull request by mroman42**
A faster and more concise Haskell implementation using immutable structures.

### CODE REVIEW

**Comment by mroman42** [comment]
I am concerned about two problems here:
- The resolution of the standard clock is maybe too small
- The lazy evaluation could prevent some benchmarks to be really evaluated

**Comment by mroman42** [comment]
I am trying to solve those problems using the Criterion library for benchmarking in Haskell.

**Comment by mroman42** [comment]
At the end, the Criterion library uses a similar timing method as we are using already. The source code can be read here: https://hackage.haskell.org/package/criterion-0.8.0.1/docs/src/Criterion-Measurement.html#time_

**Comment by mroman42** [comment]
There is a solution here for the problem: http://stackoverflow.com/questions/14163072/how-to-force-evaluation-in-haskell/14163112#14163112

**Comment by JJ** [comment]
So let's see if I got this correctly. It's being evaluated, right? Because `deepseq` is not used on the code.

**Comment by JJ** [comment]
I'm getting 0s in the bitflip _and_ onemax... So either we need more resolution or it's not been evaluated.

**Comment by mroman42** [comment]
It's `deepseq` what forces them to be evaluated. I will use `seq` and `deepseq` in the code and update the pull request shortly.

**Comment by JJ** [comment]
Please remember to add your name to the paper, well deserved.

**Comment by JJ** [comment]
I don't have time to add it to the paper now. It'll stay there for the next version.

**Pull request merged**
